### ISSUE TITLE
What is the channel count of the LiDAR used in this project?

### ISSUE THREAD

**Issue by nulha** [NingMingHao/LidarCameraCalibration#1]
Hi,
I am working with the code provided in this repository and noticed that the LiDAR point clouds are being processed, but I couldn't find any information regarding the LiDAR channel count. Could you please let me know how many channels the LiDAR used in this project has?

Thanks in advance!

**Comment by NingMingHao** [comment]
Hi,

We have tried Robosense-Helios 16, Robosense-Helios 32 and Robosense BPearl. They are working fine. In theory, there is no limitation of the number of channel for the Lidar, as the lidar processing algorithm tried to estimate the checkboard based on plane estimation.

**Comment by nulha** [comment]
Thank you! :)
